#!/usr/bin/env python

import sys
import os
import os.path
from subprocess import call

rootdir = os.path.dirname(os.path.dirname(__file__))
python = os.path.join(rootdir, ".env", "bin", "python3.5")

args = [python, "-m", "srclib-python"]
args.extend(sys.argv[1:])
call(args)
